#include "common.cuh"
#include <cuda_runtime.h>
#include <stdio.h>
#include <numeric>
#include <cub/cub.cuh> // 引入 CUB 头文件


// =============================================================================
// Reduction Kernel — 从 Naive 到 Warp Shuffle 的优化演进
//
// 测试环境: N = 16M floats, BLOCK = 1024, GPU = RTX 4090 (sm_89)
//
// 版本对比:
//   naive_reduce  — 基准版本。步长从1开始倍增 (s<<=1)，相邻线程间隔跳跃访问。
//                   问题：tid % (s*2)==0 导致严重 warp divergence，大量线程空转。
//                   bank conflict: 访问模式导致 shared memory 冲突。
//
//   reduce_v0     — 修复 warp divergence。改为从高位往低位折叠 (s>>=1)，
//                   活跃线程连续排列，消除 divergence。
//                   但 bank conflict 仍然存在（步长为1时相邻地址冲突）。
//
//   reduce_v1     — 修复 bank conflict。反转折叠方向，从 blockDim/2 往下折叠，
//                   访问地址 sdata[tid] 与 sdata[tid+s] 间距 >= 32，无冲突。
//                   这是教科书标准版本。
//
//   reduce_v2     — 减少 idle thread。每个 block 在 load 阶段处理 2 倍数据
//                   (gid 和 gid+blockDim.x)，grid 数量减半，GPU 利用率提升。
//
//   reduce_v3     — unroll 最后一个 warp。当 s<=32 时，同一 warp 内天然同步，
//                   不需要 __syncthreads()。手动展开 6 步并用 volatile 防止
//                   编译器优化掉内存写入，减少同步开销。
//
//   reduce_v4     — 用 __syncwarp() 替换 volatile。比 volatile 语义更精确，
//                   明确表达 warp 内同步意图，对编译器更友好。
//
//   reduce_v5     — 完全消除 shared memory，改用 warp shuffle。
//                   __shfl_down_sync 直接在寄存器之间传递数据，
//                   每个 warp 内 reduce 后写入 smem[warp_id]，
//                   最后一个 warp 再做一次 shuffle reduce 得到最终结果。
//                   无 bank conflict，延迟最低。
// =============================================================================


// ————————Generated by claude

// ~/data/my_hpc/kernels/cuda master !7                                                                                                                                                           Py base 07:15:49
// ❯ ./build/kernels/reduction/reduction
// Mismatch at idx 0: got 1024.000000, expected 16777216.000000
// [Reductionv1] FAIL  time=1.372 ms
// bandwidth: 48.91 GB/s
// Mismatch at idx 0: got 1024.000000, expected 16777216.000000
// [Reductionnaive] FAIL  time=1.824 ms
// bandwidth: 36.78 GB/s
// Mismatch at idx 0: got 1024.000000, expected 16777216.000000
// [Reductionv0] FAIL  time=1.053 ms
// bandwidth: 63.73 GB/s
// Mismatch at idx 0: got 2048.000000, expected 16777216.000000
// [Reductionv2] FAIL  time=0.580 ms
// bandwidth: 115.78 GB/s
// Mismatch at idx 0: got 2048.000000, expected 16777216.000000
// [Reductionv3] FAIL  time=0.403 ms
// bandwidth: 166.42 GB/s
// Mismatch at idx 0: got 2048.000000, expected 16777216.000000
// [Reductionv4] FAIL  time=0.391 ms
// bandwidth: 171.62 GB/s
// Mismatch at idx 0: got 2048.000000, expected 16777216.000000
// [Reductionv5] FAIL  time=0.288 ms
// bandwidth: 232.80 GB/s
// [Reductionv5] PASS  time=0.288 ms
// bandwidth: 232.69 GB/s
// [CUB Baseline] time=0.289 ms, bandwidth: 232.17 GB/s


__global__ void reduce_v1(const float *__restrict__ in, float *__restrict__ out, int n)
{
    extern __shared__ float sdata[];
    int tid = threadIdx.x;
    int gid = blockIdx.x * blockDim.x + threadIdx.x;

    sdata[tid] = (gid < n) ? in[gid] : 0.0f;

    __syncthreads();

    for (int s = blockDim.x / 2; s > 0; s >>= 1)
    {
        if (tid < s)
        {
            sdata[tid] += sdata[tid + s];
        }
        __syncthreads();
    }

    if (tid == 0)
    {
        out[blockIdx.x] = sdata[0];
    }
}

__global__ void reduce_v2(const float *__restrict__ in, float *__restrict__ out, int n)
{
    extern __shared__ float sdata[];
    int tid = threadIdx.x;
    int gid = blockIdx.x * (blockDim.x * 2) + threadIdx.x;

    float mySum = 0.0f;
    if (gid < n) {
        mySum += in[gid];
    }
    if (gid + blockDim.x < n) {
        mySum += in[gid + blockDim.x];
    }
    sdata[tid] = mySum;
    __syncthreads();

    for (int s = blockDim.x / 2; s > 0; s >>= 1)
    {
        if (tid < s)
        {
            sdata[tid] += sdata[tid + s];
        }
        __syncthreads();
    }
    

    if (tid == 0)
    {
        out[blockIdx.x] = sdata[0];
    }
}


__global__ void reduce_v3(const float *__restrict__ in, float *__restrict__ out, int n)
{
    extern volatile __shared__ float sddata[];
    int tid = threadIdx.x;
    int gid = blockIdx.x * (blockDim.x * 2) + threadIdx.x;

    float mySum = 0.0f;
    if (gid < n) {
        mySum += in[gid];
    }
    if (gid + blockDim.x < n) {
        mySum += in[gid + blockDim.x];
    }
    sddata[tid] = mySum;
    __syncthreads();

    for (int s = blockDim.x / 2; s > 32; s >>= 1)
    {
        if (tid < s)
        {
            sddata[tid] += sddata[tid + s];
        }
        __syncthreads();
    }

    if(tid < 32) {
        sddata[tid] += sddata[tid + 32];
        sddata[tid] += sddata[tid + 16];
        sddata[tid] += sddata[tid + 8];
        sddata[tid] += sddata[tid + 4]; 
        sddata[tid] += sddata[tid + 2];
        sddata[tid] += sddata[tid + 1];
    }


    if (tid == 0)
    {
        out[blockIdx.x] = sddata[0];
    }
}


__global__ void reduce_v4(const float *__restrict__ in, float *__restrict__ out, int n)
{
    extern __shared__ float sdddata[];
    int tid = threadIdx.x;
    int gid = blockIdx.x * (blockDim.x * 2) + threadIdx.x;

    float mySum = 0.0f;
    if (gid < n) {
        mySum += in[gid];
    }
    if (gid + blockDim.x < n) {
        mySum += in[gid + blockDim.x];
    }
    sdddata[tid] = mySum;
    __syncthreads();

    for (int s = blockDim.x / 2; s > 32; s >>= 1)
    {
        if (tid < s)
        {
            sdddata[tid] += sdddata[tid + s];
        }
        __syncthreads();
    }

    if(tid < 32) {
        sdddata[tid] += sdddata[tid + 32]; __syncwarp();
        sdddata[tid] += sdddata[tid + 16]; __syncwarp();
        sdddata[tid] += sdddata[tid + 8]; __syncwarp();
        sdddata[tid] += sdddata[tid + 4]; __syncwarp();
        sdddata[tid] += sdddata[tid + 2];__syncwarp();
        sdddata[tid] += sdddata[tid + 1];__syncwarp();
    }


    if (tid == 0)
    {
        out[blockIdx.x] = sdddata[0];
    }
}

__device__ __forceinline__ float WarpReduceSum(float mySum)
{
    mySum += __shfl_down_sync(0xffffffff, mySum, 16);
    mySum += __shfl_down_sync(0xffffffff, mySum, 8);
    mySum += __shfl_down_sync(0xffffffff, mySum, 4);
    mySum += __shfl_down_sync(0xffffffff, mySum, 2);
    mySum += __shfl_down_sync(0xffffffff, mySum, 1);

    return mySum;
}

__device__ __forceinline__ float BlockReduceSum(float val)
{
    __shared__ float sdddata[32];
    int lane = threadIdx.x % 32;
    int wid = threadIdx.x / 32;
    val = WarpReduceSum(val);
    if(lane == 0)
    {
        sdddata[wid] = val;
    }
    __syncthreads();
    if(wid == 0)
    {
        val = (lane < 32) ? sdddata[lane] : 0;
        val = WarpReduceSum(val);
    }
    return val;
}


__global__ void reduce_v5_partial(const float* __restrict__ in,
                                   float* __restrict__ partial,
                                   int n) {
    float sum = 0.0f;
    const float4* in4 = reinterpret_cast<const float4*>(in);
    int n4 = n / 4;

    for (int i = blockIdx.x * blockDim.x + threadIdx.x;
         i < n4;
         i += blockDim.x * gridDim.x) {
        float4 v = in4[i];
        sum += v.x + v.y + v.z + v.w;
    }
    // 处理尾部不足 4 的元素
    int tail = n4 * 4 + threadIdx.x;
    if (tail < n) sum += in[tail];

    sum = BlockReduceSum(sum);
    if (threadIdx.x == 0) partial[blockIdx.x] = sum;
}


__global__ void reduce_v6(const float* __restrict__ in,
                                   float* __restrict__ out,
                                   int n) {
    float sum = 0.0f;
    const float4* in4 = reinterpret_cast<const float4*>(in);
    int n4 = n / 4;

    for (int i = blockIdx.x * blockDim.x + threadIdx.x;
         i < n4;
         i += blockDim.x * gridDim.x) {
        float4 v = in4[i];
        sum += v.x + v.y + v.z + v.w;
    }
    // 处理尾部不足 4 的元素
    int tail = n4 * 4 + threadIdx.x;
    if (tail < n) sum += in[tail];

    sum = BlockReduceSum(sum);
    if(threadIdx.x == 0)
    {
        atomicAdd(out, sum);
    }
}





__global__ void reduce_v5(const float *__restrict__ in, float *__restrict__ out, int n)
{
    extern __shared__ float sdddata[32];
    int tid = threadIdx.x;
    int gid = blockIdx.x * (blockDim.x * 2) + threadIdx.x;

    float mySum = 0.0f;
    if (gid < n) {
        mySum += in[gid];
    }
    if (gid + blockDim.x < n) {
        mySum += in[gid + blockDim.x];
    }
    __syncthreads();

    mySum += __shfl_down_sync(0xffffffff, mySum, 16);
    mySum += __shfl_down_sync(0xffffffff, mySum, 8);
    mySum += __shfl_down_sync(0xffffffff, mySum, 4);
    mySum += __shfl_down_sync(0xffffffff, mySum, 2);
    mySum += __shfl_down_sync(0xffffffff, mySum, 1);

    int lanbool = tid % 32;
    int lanid = tid / 32;

    if(lanbool == 0)
    {
        sdddata[lanid] = mySum;
    }
    __syncthreads();
    if(tid < 32) {
        mySum = (tid < 32) ? sdddata[lanid] : 0;
        mySum += __shfl_down_sync(0xffffffff, mySum, 16);
        mySum += __shfl_down_sync(0xffffffff, mySum, 8);
        mySum += __shfl_down_sync(0xffffffff, mySum, 4);
        mySum += __shfl_down_sync(0xffffffff, mySum, 2);
        mySum += __shfl_down_sync(0xffffffff, mySum, 1);
    }
    if (tid == 0)
    {
        out[blockIdx.x] = mySum;
    }
}

__global__ void naive_reduce(const float* __restrict__ in, float* __restrict__ out, int n)
{
    extern __shared__ float sdata[];
    int tid = threadIdx.x;
    int gid = blockIdx.x * blockDim.x + threadIdx.x;

    sdata[tid] = (gid < n) ? in[gid] : 0;
    __syncthreads();
    for(int s = 1; s < blockDim.x; s <<= 1)
    {
        if(tid % (s * 2) == 0)
            sdata[tid] += sdata[tid + s];
        __syncthreads();    
    }
    if(threadIdx.x == 0)
        out[blockIdx.x] = sdata[tid];
}

// change the naive reduce's warp Divergence 

__global__ void reduce_v0(const float* __restrict__ in, float* __restrict__ out, int n)
{
    extern __shared__ float sdata[];
    int tid = threadIdx.x;
    int gid = blockIdx.x * blockDim.x + threadIdx.x;

    sdata[tid] = (gid < n) ? in[gid] : 0;
    __syncthreads();

    for(int s = 1; s < blockDim.x;s <<= 1)
    {
        if(tid * s * 2 < blockDim.x)
        {
            
            sdata[tid * s * 2] += sdata[tid * s * 2 + s];
        }
        __syncthreads();
    }

    if(threadIdx.x == 0)
    {
        out[blockIdx.x] = sdata[tid];
    }
}



int main()
{
    const int N = 1<<24; // 16M elements
    const int BLOCK = 1024;
    const int GRID = (N + BLOCK - 1) / BLOCK;

    float *h_in = new float[N];
    for (int i = 0; i < N; ++i)
        h_in[i] = 1.0f; // 期望结果 = N

    float *d_in, *d_partial, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    reduce_v1<<<GRID, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_partial, N);

    GpuTimer timer;
    const int ITERS = 100;

    const int GRID_1 = (N + BLOCK - 1) / BLOCK;      // 32768
    const int GRID_2 = (GRID_1 + BLOCK - 1) / BLOCK; // 64
    const int GRID_3 = 1;                            // 最终轮

    float *d_partial_2;
    CUDA_CHECK(cudaMalloc(&d_partial_2, GRID_2 * sizeof(float)));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v1<<<GRID_1, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_out, N);
    }
    float ms = timer.Stop() / ITERS;
    float result;
    float ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv1", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_in);
    cudaFree(d_partial);
    cudaFree(d_out);



    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        naive_reduce<<<GRID_1, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_out, N);
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionnaive", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_in);
    cudaFree(d_partial);
    cudaFree(d_out);


    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v0<<<GRID_1, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_out, N);   // but banks conflict
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv0", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_in);
    cudaFree(d_partial);
    cudaFree(d_out);


    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v2<<<GRID_1 / 2, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_out, N);   // divide the block num
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv2", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_in);
    cudaFree(d_partial);
    cudaFree(d_out);


    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v3<<<GRID_1 / 2, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_out, N);   // now inner the warp
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv3", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_in);
    cudaFree(d_partial);
    cudaFree(d_out);


    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v4<<<GRID_1 / 2, BLOCK, BLOCK * sizeof(float)>>>(d_in, d_out, N);   // now inner the warp
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv4", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_in);
    cudaFree(d_partial);
    cudaFree(d_out);



    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v5<<<GRID / 2, BLOCK>>>(d_in, d_out, N);   // now inner the warp
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv5", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_partial);
    cudaFree(d_out);


    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, 1 * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));

    timer.Start();
    int GRID1 = 2048;
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v5_partial<<<GRID1, BLOCK>>>(d_in, d_partial, N);

        // 第二趟：对 partial 结果归约，GRID <= 1024 一个 block 搞定
        reduce_v5_partial<<<1, BLOCK>>>(d_partial, d_out, GRID1);
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv5", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_partial);
    cudaFree(d_out);


    CUDA_CHECK(cudaMalloc(&d_in, N * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_partial, GRID * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, ITERS * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, N * sizeof(float), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemset(d_out, 0, ITERS * sizeof(float)));
    timer.Start();
    for (int i = 0; i < ITERS; ++i)
    {
        reduce_v6<<<GRID1, BLOCK>>>(d_in, d_out + i, N);
    }
    ms = timer.Stop() / ITERS;
    ans = (float)N;
    CUDA_CHECK(cudaMemcpy(&result, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    allclose("Reductionv6", &result, &ans, 1, ms);
    printf("bandwidth: %.2f GB/s\n", (N * sizeof(float)) / (ms * 1e-3) / 1e9);
    cudaFree(d_partial);
    cudaFree(d_out);


    float *d_cub_out;
    CUDA_CHECK(cudaMalloc(&d_cub_out, 1 * sizeof(float)));

    // CUB 采用灵活的二次调用机制：第一次询问需要多少额外的临时显存
    void *d_temp_storage = NULL;
    size_t temp_storage_bytes = 0;
    cub::DeviceReduce::Sum(d_temp_storage, temp_storage_bytes, d_in, d_cub_out, N);

    // 分配 CUB 所需的临时显存
    CUDA_CHECK(cudaMalloc(&d_temp_storage, temp_storage_bytes));

    // CUB 预热
    cub::DeviceReduce::Sum(d_temp_storage, temp_storage_bytes, d_in, d_cub_out, N);

    timer.Start();
    for (int i = 0; i < ITERS; ++i) {
        cub::DeviceReduce::Sum(d_temp_storage, temp_storage_bytes, d_in, d_cub_out, N);
    }
    float cub_ms = timer.Stop() / ITERS;
    float cub_bw = (N * sizeof(float)) / (cub_ms * 1e-3) / 1e9;
    printf("[CUB Baseline] time=%.3f ms, bandwidth: %.2f GB/s\n", cub_ms, cub_bw);

    cudaFree(d_temp_storage);
    cudaFree(d_cub_out);
}
